package JanelaInicial;


import JanelasAtendimento.CadastroCliente;
import JanelasAtendimento.Caixa;
import JanelasAtendimento.ConsultarPedidos;
import JanelasAtendimento.Login;
import JanelasAtendimento.SelecionarItensVenda;
import JanelasEstoque.CadastroFonecedor;
import JanelasEstoque.CadastroProduto;
import JanelasEstoque.CadastroDeUsuario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danie
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        bntMenu2CadCliente = new javax.swing.JButton();
        btnMenu2CadFornecedor = new javax.swing.JButton();
        btnMenu2CadFuncionario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnMenu2Produto = new javax.swing.JButton();
        btnMenu2Consultar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnMenu2Caixa = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnMenu2Sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArquivoBMenu = new javax.swing.JMenu();
        LogarUsuario_Aq_BMenu = new javax.swing.JMenuItem();
        Sair_Aq_BMenu = new javax.swing.JMenuItem();
        Relatorio = new javax.swing.JMenuItem();
        at_Consultar_Pedido = new javax.swing.JMenu();
        AddCadatro_AT_Bmenu = new javax.swing.JMenuItem();
        NovoPedido_AT_BMenu = new javax.swing.JMenuItem();
        LocalizarCad_AT_BMenu = new javax.swing.JMenuItem();
        AbrirCaixa_AtMenu = new javax.swing.JMenuItem();
        FornecedorBMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        AjudaBmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bntMenu2CadCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bntMenu2CadCliente.setForeground(new java.awt.Color(0, 204, 51));
        bntMenu2CadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Menu2/Cliente.png"))); // NOI18N
        bntMenu2CadCliente.setText("Cliente");
        bntMenu2CadCliente.setFocusable(false);
        bntMenu2CadCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntMenu2CadCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntMenu2CadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMenu2CadClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(bntMenu2CadCliente);

        btnMenu2CadFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu2CadFornecedor.setForeground(new java.awt.Color(255, 51, 51));
        btnMenu2CadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Menu2/Fornecedor.png"))); // NOI18N
        btnMenu2CadFornecedor.setText("Fornecedor");
        btnMenu2CadFornecedor.setFocusable(false);
        btnMenu2CadFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu2CadFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenu2CadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2CadFornecedorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenu2CadFornecedor);

        btnMenu2CadFuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu2CadFuncionario.setForeground(new java.awt.Color(51, 102, 255));
        btnMenu2CadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Menu2/Funcionario.png"))); // NOI18N
        btnMenu2CadFuncionario.setText("Funcionario");
        btnMenu2CadFuncionario.setFocusable(false);
        btnMenu2CadFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu2CadFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenu2CadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2CadFuncionarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenu2CadFuncionario);
        jToolBar1.add(jSeparator1);

        btnMenu2Produto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu2Produto.setForeground(new java.awt.Color(204, 102, 0));
        btnMenu2Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Menu2/Produtos.png"))); // NOI18N
        btnMenu2Produto.setText("Produtos");
        btnMenu2Produto.setFocusable(false);
        btnMenu2Produto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu2Produto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnMenu2Produto);

        btnMenu2Consultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu2Consultar.setForeground(new java.awt.Color(102, 102, 102));
        btnMenu2Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Menu2/codigoBrr.png"))); // NOI18N
        btnMenu2Consultar.setText("Consultar");
        btnMenu2Consultar.setFocusable(false);
        btnMenu2Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu2Consultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnMenu2Consultar);
        jToolBar1.add(jSeparator2);

        btnMenu2Caixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu2Caixa.setForeground(new java.awt.Color(255, 153, 51));
        btnMenu2Caixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/caixa2.png"))); // NOI18N
        btnMenu2Caixa.setText("Caixa");
        btnMenu2Caixa.setFocusable(false);
        btnMenu2Caixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu2Caixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenu2Caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2CaixaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenu2Caixa);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 153, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Localizar.png"))); // NOI18N
        jButton7.setText("Vendas");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator3);

        btnMenu2Sair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMenu2Sair.setForeground(new java.awt.Color(204, 0, 0));
        btnMenu2Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Menu2/Sair.png"))); // NOI18N
        btnMenu2Sair.setText("Sair");
        btnMenu2Sair.setFocusable(false);
        btnMenu2Sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu2Sair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenu2Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2SairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenu2Sair);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ig[.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2881, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ArquivoBMenu.setText("Arquivos");

        LogarUsuario_Aq_BMenu.setText("Logar Usuario");
        LogarUsuario_Aq_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogarUsuario_Aq_BMenuActionPerformed(evt);
            }
        });
        ArquivoBMenu.add(LogarUsuario_Aq_BMenu);

        Sair_Aq_BMenu.setText("Sair");
        Sair_Aq_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_Aq_BMenuActionPerformed(evt);
            }
        });
        ArquivoBMenu.add(Sair_Aq_BMenu);

        Relatorio.setText("Relatorios");
        ArquivoBMenu.add(Relatorio);

        jMenuBar1.add(ArquivoBMenu);

        at_Consultar_Pedido.setText("Atendimento");

        AddCadatro_AT_Bmenu.setText("Novo Cadastro");
        AddCadatro_AT_Bmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCadatro_AT_BmenuActionPerformed(evt);
            }
        });
        at_Consultar_Pedido.add(AddCadatro_AT_Bmenu);

        NovoPedido_AT_BMenu.setText("Novo Pedido");
        NovoPedido_AT_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoPedido_AT_BMenuActionPerformed(evt);
            }
        });
        at_Consultar_Pedido.add(NovoPedido_AT_BMenu);

        LocalizarCad_AT_BMenu.setText("Consultar Pedidos");
        LocalizarCad_AT_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocalizarCad_AT_BMenuActionPerformed(evt);
            }
        });
        at_Consultar_Pedido.add(LocalizarCad_AT_BMenu);

        AbrirCaixa_AtMenu.setText("Abrir Caixa");
        AbrirCaixa_AtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCaixa_AtMenuActionPerformed(evt);
            }
        });
        at_Consultar_Pedido.add(AbrirCaixa_AtMenu);

        jMenuBar1.add(at_Consultar_Pedido);

        FornecedorBMenu.setText("Estoque");

        jMenuItem1.setText("Cadastrar item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        FornecedorBMenu.add(jMenuItem1);

        jMenuBar1.add(FornecedorBMenu);

        AjudaBmenu.setText("Ajuda");
        jMenuBar1.add(AjudaBmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddCadatro_AT_BmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCadatro_AT_BmenuActionPerformed
     CadastroCliente Cad = new CadastroCliente(this,true);
     Cad.setVisible(true);
        
    }//GEN-LAST:event_AddCadatro_AT_BmenuActionPerformed

    private void LogarUsuario_Aq_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogarUsuario_Aq_BMenuActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
            

    }//GEN-LAST:event_LogarUsuario_Aq_BMenuActionPerformed

    private void Sair_Aq_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_Aq_BMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Sair_Aq_BMenuActionPerformed

    private void NovoPedido_AT_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoPedido_AT_BMenuActionPerformed
        // Tela de pedidos
        SelecionarItensVenda item = new SelecionarItensVenda();
        item.setVisible(true);
    }//GEN-LAST:event_NovoPedido_AT_BMenuActionPerformed

    private void LocalizarCad_AT_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalizarCad_AT_BMenuActionPerformed
        // Consultar Cadastro
        ConsultarPedidos cad = new ConsultarPedidos();
        cad.setVisible(true);
    }//GEN-LAST:event_LocalizarCad_AT_BMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Cadastro de protudos
        CadastroProduto cadp = new CadastroProduto();
        cadp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AbrirCaixa_AtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCaixa_AtMenuActionPerformed
        // Caixa
        Caixa cx = new Caixa();
        cx.setVisible(true);
    }//GEN-LAST:event_AbrirCaixa_AtMenuActionPerformed

    private void bntMenu2CadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMenu2CadClienteActionPerformed
        // TODO add your handling code here:
        CadastroCliente Cad = new CadastroCliente(this,true);
        Cad.setVisible(true);
    }//GEN-LAST:event_bntMenu2CadClienteActionPerformed

    private void btnMenu2SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2SairActionPerformed
        // sair do sistema menu2
        System.exit(0);
    }//GEN-LAST:event_btnMenu2SairActionPerformed

    private void btnMenu2CadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2CadFornecedorActionPerformed
        // Cadastra fornecedor
        CadastroFonecedor Cfor = new CadastroFonecedor();
        Cfor.setVisible(true);
    }//GEN-LAST:event_btnMenu2CadFornecedorActionPerformed

    private void btnMenu2CadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2CadFuncionarioActionPerformed
        // Cadastro De funcionario
        CadastroDeUsuario UsuCad = new CadastroDeUsuario();
        UsuCad.setVisible(true);
    }//GEN-LAST:event_btnMenu2CadFuncionarioActionPerformed

    private void btnMenu2CaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2CaixaActionPerformed
        // entrar no caixa
        Caixa btnCx = new Caixa();
        btnCx.setVisible(true);
    }//GEN-LAST:event_btnMenu2CaixaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // entrar na tela de pedido
        SelecionarItensVenda btnM2Venda = new SelecionarItensVenda();
        btnM2Venda.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirCaixa_AtMenu;
    private javax.swing.JMenuItem AddCadatro_AT_Bmenu;
    private javax.swing.JMenu AjudaBmenu;
    private javax.swing.JMenu ArquivoBMenu;
    private javax.swing.JMenu FornecedorBMenu;
    private javax.swing.JMenuItem LocalizarCad_AT_BMenu;
    private javax.swing.JMenuItem LogarUsuario_Aq_BMenu;
    private javax.swing.JMenuItem NovoPedido_AT_BMenu;
    private javax.swing.JMenuItem Relatorio;
    private javax.swing.JMenuItem Sair_Aq_BMenu;
    private javax.swing.JMenu at_Consultar_Pedido;
    private javax.swing.JButton bntMenu2CadCliente;
    private javax.swing.JButton btnMenu2CadFornecedor;
    private javax.swing.JButton btnMenu2CadFuncionario;
    private javax.swing.JButton btnMenu2Caixa;
    private javax.swing.JButton btnMenu2Consultar;
    private javax.swing.JButton btnMenu2Produto;
    private javax.swing.JButton btnMenu2Sair;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
