package JanelaInicial;


import JanelasAtendimento.CadastroCliente;
import JanelasAtendimento.ConsultarPedidos;
import JanelasAtendimento.Login;
import JanelasAtendimento.SelecionarItensVenda;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danie
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArquivoBMenu = new javax.swing.JMenu();
        LogarUsuario_Aq_BMenu = new javax.swing.JMenuItem();
        Sair_Aq_BMenu = new javax.swing.JMenuItem();
        Relatorio = new javax.swing.JMenuItem();
        at_Consultar_Pedido = new javax.swing.JMenu();
        AddCadatro_AT_Bmenu = new javax.swing.JMenuItem();
        NovoPedido_AT_BMenu = new javax.swing.JMenuItem();
        LocalizarCad_AT_BMenu = new javax.swing.JMenuItem();
        AbrirCaixa_AtMenu = new javax.swing.JMenuItem();
        FornecedorBMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        AjudaBmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ArquivoBMenu.setText("Arquivos");

        LogarUsuario_Aq_BMenu.setText("Logar Usuario");
        LogarUsuario_Aq_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogarUsuario_Aq_BMenuActionPerformed(evt);
            }
        });
        ArquivoBMenu.add(LogarUsuario_Aq_BMenu);

        Sair_Aq_BMenu.setText("Sair");
        Sair_Aq_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_Aq_BMenuActionPerformed(evt);
            }
        });
        ArquivoBMenu.add(Sair_Aq_BMenu);

        Relatorio.setText("Relatorios");
        ArquivoBMenu.add(Relatorio);

        jMenuBar1.add(ArquivoBMenu);

        at_Consultar_Pedido.setText("Atendimento");

        AddCadatro_AT_Bmenu.setText("Novo Cadastro");
        AddCadatro_AT_Bmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCadatro_AT_BmenuActionPerformed(evt);
            }
        });
        at_Consultar_Pedido.add(AddCadatro_AT_Bmenu);

        NovoPedido_AT_BMenu.setText("Novo Pedido");
        NovoPedido_AT_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoPedido_AT_BMenuActionPerformed(evt);
            }
        });
        at_Consultar_Pedido.add(NovoPedido_AT_BMenu);

        LocalizarCad_AT_BMenu.setText("Consultar Pedidos");
        LocalizarCad_AT_BMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocalizarCad_AT_BMenuActionPerformed(evt);
            }
        });
        at_Consultar_Pedido.add(LocalizarCad_AT_BMenu);

        AbrirCaixa_AtMenu.setText("Abrir Caixa");
        at_Consultar_Pedido.add(AbrirCaixa_AtMenu);

        jMenuBar1.add(at_Consultar_Pedido);

        FornecedorBMenu.setText("Estoque");

        jMenuItem1.setText("Cadastrar item");
        FornecedorBMenu.add(jMenuItem1);

        jMenuBar1.add(FornecedorBMenu);

        AjudaBmenu.setText("Ajuda");
        jMenuBar1.add(AjudaBmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddCadatro_AT_BmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCadatro_AT_BmenuActionPerformed
     CadastroCliente Cad = new CadastroCliente(this,true);
     Cad.setVisible(true);
        
    }//GEN-LAST:event_AddCadatro_AT_BmenuActionPerformed

    private void LogarUsuario_Aq_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogarUsuario_Aq_BMenuActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
            

    }//GEN-LAST:event_LogarUsuario_Aq_BMenuActionPerformed

    private void Sair_Aq_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_Aq_BMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Sair_Aq_BMenuActionPerformed

    private void NovoPedido_AT_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoPedido_AT_BMenuActionPerformed
        // Tela de pedidos
        SelecionarItensVenda item = new SelecionarItensVenda();
        item.setVisible(true);
    }//GEN-LAST:event_NovoPedido_AT_BMenuActionPerformed

    private void LocalizarCad_AT_BMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalizarCad_AT_BMenuActionPerformed
        // Consultar Cadastro
        ConsultarPedidos cad = new ConsultarPedidos();
        cad.setVisible(true);
    }//GEN-LAST:event_LocalizarCad_AT_BMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirCaixa_AtMenu;
    private javax.swing.JMenuItem AddCadatro_AT_Bmenu;
    private javax.swing.JMenu AjudaBmenu;
    private javax.swing.JMenu ArquivoBMenu;
    private javax.swing.JMenu FornecedorBMenu;
    private javax.swing.JMenuItem LocalizarCad_AT_BMenu;
    private javax.swing.JMenuItem LogarUsuario_Aq_BMenu;
    private javax.swing.JMenuItem NovoPedido_AT_BMenu;
    private javax.swing.JMenuItem Relatorio;
    private javax.swing.JMenuItem Sair_Aq_BMenu;
    private javax.swing.JMenu at_Consultar_Pedido;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
